# Kubernetes Cert
cert:
  # 签发集群整数保存目录，默认签发10年有限期证书
  dir: /opt/certs
  # 签发证书大小
  size: 2048

# Etcd
etcd:
  # etcd 版本
  version: 3.4.13
  # etcd 数据目录
  data_dir: "/data/etcd"

# High Availability
# kube-apiserver负载均衡的信息
# 如使用haproxy + keepalived请填写VIP及端口
# 如使用公有云负载均衡请填写负载均衡IP及端口（需再安装之前自行配置）
# 如使用域名，需提前配置解析。不使用域名时，请注释掉
# 如使用haproxy + keepalived ，并且跟master节点部署在一起时，请修改port以避免端口冲突
loadbalance:
  ip: 192.168.199.254
  netmask: 24
  port: 9443
  #domain_name: apiserver.k8sre.com

# Kubernetes
kubernetes:
  # kubernetes 版本
  version: v1.18.18
  # 集群Pod网段
  podSubnet: 10.64.0.0/12
  # 集群Service网段
  serviceSubnet: 10.80.0.0/16
  # kubelet 数据目录
  kubelet_dir: "/data/kubernetes/kubelet"
  # cni-plugins: https://github.com/containernetworking/plugins
  cni_plugins_version: v0.8.7
  # kubernetes 日志目录
  log: "/data/kubernetes/logs"
  # 集群DNS域名
  clusterDns: cluster.wx
  # 集群名称
  clusterName: wx-k8s
  # 集群管理员
  clusterAdminName: wx-k8s-admin

# Containerd
container_runtime: docker
docker:
  version: 19.0.15
  ubuntuversion: 5:19.03.15~3-0~ubuntu-bionic
  root: "/data/kubernetes/docker"
  registry-mirrors: "https://l0z7rpjj.mirror.aliyuncs.com"
  state: "/run/docker"
critools:
  version: v1.21.0
containerd:
  # containerd 版本
  version: 1.4.4-1
  # containerd 持久化数据目录
  root: "/data/kubernetes/containerd"
  # containerd 临时数据目录
  state: "/run/containerd"
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  metrics:
    address: ""
    grpc_histogram: false
  cri:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.3"
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    SystemdCgroup: true
#  registries:
#    "docker.io": "https://registry-1.docker.io"
#    "k8s.gcr.io": "https://registry.aliyuncs.com/k8sxio"

# Network Plugin
network_plugin: cilium
calico:
  version: v3.19.0
  network_mode: ipip
flannel:
  version: v0.13.0
  network_mode: vxlan
# cilium need linux kernel >= 4.9.17
cilium:
  version: v1.9.8

# Addons
dns:
  coredns_version: 1.8.0
  enable_nodelocaldns: true
  nodelocaldns_version: 1.17.0
  nodelocaldns_ip: 169.254.20.10
metrics_server:
  version: v0.4.1
helm:
  helm_version: v3.6.0
ingress:
  ingress_version: v0.40.0
  webhook_version: v1.15.1
