---
- name: "Install nginx"
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: "Install nginx"
  yum:
    name: nginx
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: "Generate nginx.conf"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - restart nginx

- name: "remove sites-available dir"
  file:
    path: "/etc/nginx/sites-available"
    state: absent

- name: "remove sites-enabled dir"
  file:
    path: "/etc/nginx/sites-enabled"
    state: absent
