---
- name: "Install haproxy"
  yum:
    name: haproxy
    state: present

- name: "Generate haproxy.cfg"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify:
    - restart_haproxy
