---
- name: Get cri-tools
  get_url:
    url: "https://ghproxy.com/https://github.com/kubernetes-sigs/cri-tools/releases/download/{{critools.version}}/crictl-{{critools.version}}-linux-amd64.tar.gz"
    dest: /tmp/
  tags: cri_tools

- name: "Config cri-tools"
  template:
    src: "crictl.yaml.j2"
    dest: "/etc/crictl.yaml"
    owner: root
    group: root
    mode: 0644
  tags: cri_tools

- name: Install cri-tools
  unarchive:
    src: "/tmp/crictl-{{critools.version}}-linux-amd64.tar.gz"
    dest: /usr/bin/
    remote_src: yes
  tags: cri_tools
  notify:
    - Get crictl completion
    - Install crictl completion
