---
- name: restart_etcd
  command: /bin/true
  notify:
    - reload etcd
    - wait_for_etcd_up

- name: reload_etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: etcd_restarted

- name: wait_for_etcd_up
  uri:
    url: "https://{{ ansible_default_ipv4.address }}:2379/health"
    validate_certs: no
    client_cert: "/etc/etcd/pki/etcd-healthcheck-client.pem"
    client_key: "/etc/etcd/pki/etcd-healthcheck-client.key"
  register: result
  until: result.status is defined and result.status == 200
  retries: 60
  delay: 1
