---
- name: "Generate calico yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "calico-etcd.yaml.j2", dest: "/tmp/calico-etcd.yaml"}
  tags: calico

- name: "删除默认cni-plugins配置"
  file:
    path: "/etc/cni/net.d/cni-default.conf"
    state: absent

- name: "Deploy calico"
  shell: "kubectl apply -f /tmp/calico-etcd.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: calico
