---
- name: "Generate flannel yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "flannel.yaml.j2", dest: "/tmp/flannel.yaml"}
  tags: flannel

- name: "删除默认cni-plugins配置"
  file:
    path: "/etc/cni/net.d/cni-default.conf"
    state: absent

- name: "Deploy flannel"
  shell: "kubectl apply -f /tmp/flannel.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: flannel
