---
- name: restart_docker
  command: /bin/true
  notify:
    - restart_docker
    - wait_for_docker

- name: restart_docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: wait_for_docker
  command: "docker images ls -q"
  register: docker_ready
  retries: 8
  delay: 4
  until: docker_ready.rc == 0

- name: restart_containerd
  command: /bin/true
  notify:
    - restart_containerd
    - wait_for_containerd

- name: restart_containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: wait_for_containerd
  command: "ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0
