---
docker__ubuntu_repo_base_url: "https://download.docker.com/linux/ubuntu"
docker_ubuntu_repo_gpgkey: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo_key_info.repo_keys: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_ubuntu_repo_component: "stable"

docker_repo_key_info:
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - '{{ docker_ubuntu_repo_repokey }}'

docker_repo_info:
  repos:
    - >
      deb {{ docker_ubuntu_repo_base_url }}
      {{ ansible_distribution_release|lower }}
      {{ docker_ubuntu_repo_component }}
