---
- name: "Install dependency"
  yum:
    name: "{{ item.line }}"
    state: installed
  with_items:
    - {line: 'libnetfilter_cthelper'}
    - {line: 'libnetfilter_cttimeout'}
    - {line: 'libnetfilter_queue'}
    - {line: 'conntrack-tools'}
    - {line: 'ipvsadm'}
    - {line: 'ipset'}
    - {line: 'socat'}
  when: ansible_os_family == "RedHat"
  tags: worker_app

- name: "Install dependency"
  apt:
    name: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'libnetfilter-cthelper0'}
    - {line: 'libnetfilter-cttimeout1'}
    - {line: 'libnetfilter-queue1'}
    - {line: 'conntrack'}
    - {line: 'aufs-tools'}
    - {line: 'ipvsadm'}
    - {line: 'ipset'}
    - {line: 'socat'}
  when: ansible_pkg_mgr == 'apt'
  tags: worker_app

- name: "Create kubernetes directory"
  file:
    path: "{{ item.line }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - {line: '/etc/kubernetes/pki'}
    - {line: '/etc/kubernetes/manifests'}
    - {line: "{{ kubernetes.kubelet_dir }}"}
  tags: dir

- name: "判断kubelet二进制文件是否存在"
  shell: which kubelet
  ignore_errors: true
  register: kubelet_ready

- name: "Install kubelet"
  when: kubelet_ready.rc != 0
  get_url:
    url: "https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/{{ kubernetes.version  }}/bin/linux/amd64/kubelet"
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0750
  tags: install_worker

- name: "判断kube-proxy二进制文件是否存在"
  shell: which kube-proxy
  ignore_errors: true
  register: kube_proxy_ready

- name: "Install kube-proxy"
  when: kube_proxy_ready.rc != 0
  get_url:
    url: "https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/{{ kubernetes.version  }}/bin/linux/amd64/kube-proxy"
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0750
  tags: install_worker

- name: "Distribution worker certs"
  copy:
    src: "{{ item.line }}"
    dest: "/etc/kubernetes/pki/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {line: "{{ cert.dir }}/ca.pem"}
    - {line: "{{ cert.dir }}/ca.key"}
    - {line: "{{ cert.dir }}/{{ ansible_default_ipv4.address }}/kube-proxy.pem"}
    - {line: "{{ cert.dir }}/{{ ansible_default_ipv4.address }}/kube-proxy.key"}
    - {line: "{{ cert.dir }}/token"}
  tags:
    - dis_worker_certs
    - dis_certs

- name: "Copy bootstrap-token"
  copy:
    src: "{{ cert.dir }}/token"
    dest: "/etc/kubernetes/pki/"
    owner: root
    group: root
    mode: 0640
  tags:
    - get_token
    - bootstrap_token

- name: "Get bootstrap-token-id"
  shell: cat /etc/kubernetes/pki/token | grep -v "^#" | awk -F '.' '{print $1}'
  register: token_id
  tags:
    - get_token_id
    - bootstrap_token

- name: "Get bootstrap-token-secret"
  shell: cat /etc/kubernetes/pki/token | grep -v "^#" | awk -F '.' '{print $2}'
  register: token_secret
  tags:
    - get_token_secret
    - bootstrap_token

- name: "Check if kube-apiserver:kubelet-apis exists"
  shell: kubectl get clusterrolebinding kube-apiserver:kubelet-apis
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: kubelet_apis_ready
  tags: bootstrap

- name: "授予kube-apiserver访问kubelet API权限"
  when: kubelet_apis_ready.rc != 0
  shell: kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if bootstrap-token exists"
  shell: kubectl -n kube-system get secret bootstrap-token-{{ token_id.stdout }}
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: bootstrap_token_ready
  tags: bootstrap

- name: "创建bootstrap-token secret"
  when: bootstrap_token_ready.rc != 0
  shell: kubectl -n kube-system create secret generic bootstrap-token-{{ token_id.stdout }} --type 'bootstrap.kubernetes.io/token' --from-literal description="cluster bootstrap token" --from-literal token-id={{ token_id.stdout }} --from-literal token-secret={{ token_secret.stdout }} --from-literal usage-bootstrap-authentication=true --from-literal usage-bootstrap-signing=true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if clusterrolebinding kubelet-bootstrap exists"
  shell: kubectl get clusterrolebinding kubelet-bootstrap
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: kubelet_bootstrap_ready
  tags: bootstrap

- name: "绑定group system:bootstrappers 和 clusterrole system:node-bootstrapper"
  when: kubelet_bootstrap_ready.rc != 0
  shell: kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if clusterrole approve-node-server-renewal-csr exists"
  shell: kubectl get clusterrole approve-node-server-renewal-csr
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: approve_node_server_renewal_csr_ready
  tags: bootstrap

- name: "创建自动批准相关 CSR 请求的 ClusterRole"
  when: approve_node_server_renewal_csr_ready.rc != 0
  shell: kubectl create clusterrole approve-node-server-renewal-csr --verb=create --resource=certificatesigningrequests/selfnodeserver --resource-name=certificates.k8s.io
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if node-autoapprove-csrs-for-group exists"
  shell: kubectl get clusterrolebinding node-autoapprove-csrs-for-group
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: node_autoapprove_csrs_for_group_ready
  tags: bootstrap

- name: "自动批准 system:bootstrappers 组用户 TLS bootstrapping 首次申请证书的 CSR 请求"
  when: node_autoapprove_csrs_for_group_ready.rc != 0
  shell: kubectl create clusterrolebinding node-autoapprove-csrs-for-group --clusterrole=system:certificates.k8s.io:certificatesigningrequests:nodeclient --group=system:bootstrappers
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if clusterrolebinding  node-client-cert-renewal exists"
  shell: kubectl get clusterrolebinding node-client-cert-renewal
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: node_client_cert_renewal_ready
  tags: bootstrap

- name: "自动批准 system:nodes 组用户更新 kubelet 自身与 apiserver 通讯证书的 CSR 请求"
  when: node_client_cert_renewal_ready.rc != 0
  shell: kubectl create clusterrolebinding node-client-cert-renewal --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeclient --group=system:nodes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Check if clusterrolebinding node-server-cert-renewal exists"
  shell: kubectl get clusterrolebinding node-server-cert-renewal
  ignore_errors: yes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: node_server_cert_renewal_ready
  tags: bootstrap

- name: "自动批准 system:nodes 组用户更新 kubelet 10250 api 端口证书的 CSR 请求"
  when: node_server_cert_renewal_ready.rc != 0
  shell: kubectl create clusterrolebinding node-server-cert-renewal --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeserver --group=system:nodes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: "Distribution worker kubeconfig"
  template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0640
    dest: "{{ item.dest }}"
  with_items:
    - {src: "bootstrap.kubeconfig.j2",dest: "/etc/kubernetes/bootstrap.kubeconfig" }
    - {src: "proxy.kubeconfig.j2",dest: "/etc/kubernetes/proxy.kubeconfig" }
  tags: dis_worker_kubeconfig

- name: "Distribution worker config"
  template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0640
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kubelet.conf.j2",dest: "/etc/kubernetes/kubelet.conf" }
    - {src: "10-kubelet.conf.j2",dest: "/etc/kubernetes/kubelet" }
    - {src: "kube-proxy.conf.j2",dest: "/etc/kubernetes/kube-proxy.conf" }
  tags: dis_worker_config

- name: "Distribution worker system unit"
  template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kubelet.service.j2",dest: "/usr/lib/systemd/system/kubelet.service" }
    - {src: "kube-proxy.service.j2",dest: "/usr/lib/systemd/system/kube-proxy.service" }
  tags: dis_worker_systemd
  when: ansible_os_family == "RedHat"

- name: "Distribution worker system unit"
  template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kubelet.service.j2",dest: "/lib/systemd/system/kubelet.service" }
    - {src: "kube-proxy.service.j2",dest: "/lib/systemd/system/kube-proxy.service" }
  tags: dis_worker_systemd
  when: ansible_os_family == "Debian"

  #- name: "暂停1分钟"
  #  pause: minutes=1
  #
  #- name: "获取Pending状态的csr"
  #  shell: kubectl get csr| grep Pending | awk '{print $1}'|tr '\n' ' '
  #  register: approve_csr
  #
  #- name: "approve csr"
  #  shell: kubectl certificate approve {{ approve_csr.stdout }}
  #  delegate_to: "{{ groups['master'][0] }}"
  #  run_once: true

- name: "Restart kubelet"
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: restart_kubelet

- name: "Waiting kubelet starting"
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 10250
    delay: 5
    sleep: 2
  tags: healthcheck

- name: "kubelet health check"
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:10248/healthz"
    return_content: yes
    validate_certs: no
  register: kubelet
  failed_when: "'ok' not in kubelet.content"
  connection: local
  tags: healthcheck

- name: "Restart kube-proxy"
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: restart_proxy

- name: "Waiting kube-proxy starting"
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 10256
    delay: 5
    sleep: 2
  tags: healthcheck

- name: "kube-proxy health check"
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:10256/healthz"
    return_content: yes
    validate_certs: no
    status_code: 200
  register: proxy
  connection: local
  tags: healthcheck

- name: "删除bootstrap-token文件"
  file:
    path: "/etc/kubernetes/pki/token"
    state: absent
  tags:
    - delete_token
    - bootstrap_token

- name: "Create taint for master"
  shell: "kubectl taint nodes {{ hostvars[item].hostname }}-{{ item }} node-role.kubernetes.io/master=:NoSchedule"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  with_items:
    - "{{ groups['master'] }}"
  tags:
    - create_master_label
    - create_master_taint
    - create_label

- name: "Create label for master"
  shell: "kubectl label nodes {{ hostvars[item].hostname }}-{{ item }} node-role.kubernetes.io/master="
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  with_items:
    - "{{ groups['master'] }}"
  tags:
    - create_master_label
    - create_label

- name: "Create label for worker"
  shell: "kubectl label nodes {{ hostvars[item].hostname }}-{{ item }} node-role.kubernetes.io/worker="
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  with_items:
    - "{{ groups['worker'] }}"
  tags:
    - create_worker_label
    - create_label
