---
- name: restart containerd
  command: /bin/true
  notify:
    - Containerd | restart containerd
    - Containerd | wait for containerd

- name: Containerd | restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Containerd | wait for containerd
  command: "ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0
