---
- name: "Add containerd repo"
  yum_repository:
    file: containerd
    name: "containerd"
    description: "Containerd Stable - $basearch"
    baseurl: "https://mirrors.bfsu.edu.cn/docker-ce/linux/centos/7/$basearch/stable"
    gpgkey: "https://mirrors.bfsu.edu.cn/docker-ce/linux/centos/gpg"
    gpgcheck: yes
    enabled: yes
  tags: containerd_repo

- name: "Install containerd"
  yum:
    update_cache: yes
    enablerepo: containerd
    name: 'containerd.io{% if containerd.version is defined and containerd.version != ""  %}-{{ containerd.version }}{% endif %}'
    state: installed
  tags: install_containerd

- name: "Create containerd directory"
  file:
    path: "{{ containerd.root }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: containerd_config

- name: "Set containerd config"
  template:
    src: "config.toml.j2"
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644
  tags: containerd_config
  notify:
    - restart_containerd
