---
- import_tasks: ../docker/tasks/main.yml
  when:
    - network_plugin == 'docker'
  tags:
    - docker

- import_tasks: ../containerd/tasks/main.yml
  when:
    - network_plugin == 'containerd'
  tags:
    - containerd
