---
- import_tasks: ../docker/tasks/main.yml
  when:
    - container_runtime == 'docker'
  tags:
    - docker

- import_tasks: ../containerd/tasks/main.yml
  when:
    - container_runtime == 'containerd'
  tags:
    - containerd
