---
- name: restart docker
  command: /bin/true
  notify:
    - Docker | restart docker
    - Docker | wait for docker

- name: Docker | restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Docker | wait for docker
  command: "docker images ls -q"
  register: docker_ready
  retries: 8
  delay: 4
  until: docker_ready.rc == 0
