---
- name: "Generate ingress yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "ingress.yaml.j2", dest: "/tmp/ingress.yaml"}
  tags: ingress

- name: "Deploy ingress"
  shell: "kubectl apply -f /tmp/ingress.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: ingress

- name: "Generate ingress configmap yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "ingress-configmap.yaml.j2", dest: "/tmp/ingress-configmap.yaml"}
  tags: ingress

- name: "Deploy ingress configmap"
  shell: "kubectl apply -f /tmp/ingress-configmap.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: ingress
